# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
archives_base_name=kaleidoscope_hodgepodge

# Mod Properties
mod_version=1.1.0-fabric+mc26.3
maven_group=com.moigferdsrte.kaleidoscopehodgepodge

# Dependencies
fabric_api_version=0.161.0+26.3
kaleidoscope_cookery_version=1.5.0.1
kaleidoscope_tavern_version=1.2.0.9
kaleidoscope_nether_version=1.1.11
kaleidoscope_end_version=1.0.13
forge_config_api_version=26.3.1
jei_version=26.3-fabric:31.3.0.18
